[package]
name = "illness"
version = "0.1.1"
authors = ["haze"]

[dependencies]
rocket = "0.3.8"
rocket_codegen = "0.3.8"
rocket_contrib = "*"
diesel = { version = "1.1", features = ["sqlite", "r2d2"] }

serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

rand = "0.4.2"